### ISSUE TITLE
Modifications for February 2024

### ISSUE THREAD

**Issue by ryanpcmcquen** [Tech-How/Light-Theme-for-YouTube-Music#4]
I added this to the bottom of the stylesheet, because the app drawer dark background was persisting:

```css
#contentContainer.tp-yt-app-drawer,
.style-scope.ytmusic-app {
    background-color: #F4F4F4;
}
```
